USE DataWarehouse;
GO

-- Explore All Objects in the Database
SELECT *
FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- Explore all countries our customers come from
SELECT DISTINCT 
    country
FROM gold.dim_customers

-- Explore All Categories "The Major Divisions"
SELECT DISTINCT 
    category,
    subcategory,
    product_name
FROM gold.dim_products
ORDER BY 1, 2, 3

-- Find the date of the first and last order
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(year, MIN(order_date), MAX(order_date))
FROM gold.fact_sales

-- Find the youngest and oldest customer
SELECT 
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(year,  MIN(birthdate),GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(year,  MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

-- Find the total Sales
SELECT SUM(sales_amt) AS total_sales FROM gold.fact_sales
-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales
-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales
-- Find the total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
-- Always compare it using distinct 
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
-- Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
-- Distinct
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products
-- Find the total number of customers
SELECT COUNT(customer_key) AS total_products FROM gold.dim_customers
-- Find the total number of customers that has placed an order
SELECT 
    COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales


-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amt) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Avg_Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' AS measure_name, COUNT(product_key) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers



-- Find total customers by countries
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-- Find total customers by gender
-- Need Fix
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
    category,
    COUNT(product_key) AS Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC
-- What is the average costs in each category?
SELECT 
    category,
   AVG(cost) AS Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC
-- What is the total revenue generated for each category?
SELECT
    p.category AS Category,
    SUM(s.sales_amt) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p  
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
-- Find total revenue is generated by each customer
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amt) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c  
ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC
-- What is the distribution of sold items across countries?

SELECT 
    c.country,
    SUM(f.quantity) total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c  
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC


-- What are the 5 worst-peforming products in terms of sales?

SELECT TOP 5
    p.product_name,
    SUM(f.sales_amt) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p  
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

SELECT 
    *
FROM (
    SELECT 
        p.product_name,
        SUM(f.sales_amt) total_revenue, 
        ROW_NUMBER () OVER (ORDER BY SUM(f.sales_amt) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p  
    ON p.product_key = f.product_key
    GROUP BY p.product_name )
t WHERE rank_products <= 5
